import type { Prompt } from '../../engine/types';

/**
 * مثّلها — Act It Out.
 * Silent acting. Keep every prompt to one recognisable *situation*, not a
 * noun. If it can be mimed in under 10 seconds, it is a good card.
 */
export const ACT_PROMPTS: Prompt[] = [
  {
    id: 'act-001',
    game: 'act',
    ar: 'واحد يدوّر موقف سيارة في الأفنيوز ويوم الخميس',
    en: 'Someone hunting for a parking spot at The Avenues on a Thursday',
    rooms: ['friends', 'kuwait', 'diwaniya'],
    difficulty: 'easy',
    level: 'family',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-002',
    game: 'act',
    ar: 'ربعك يقول «طالع من البيت» وهو باقي نايم',
    en: 'A friend saying "I am on my way" while still in bed',
    rooms: ['friends', 'diwaniya', 'kuwait'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-003',
    game: 'act',
    ar: 'تفتح كيس الطلب وتكتشف إنهم نسوا الدقوس',
    en: 'Opening the takeaway bag and finding they forgot the daqoos',
    rooms: ['friends', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'family',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-004',
    game: 'act',
    ar: 'واحد يبي يطلع من الديوانية ويظل نص ساعة يسلّم',
    en: 'Trying to leave a gathering but still saying goodbye half an hour later',
    rooms: ['friends', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-005',
    game: 'act',
    ar: 'يدوّر تلفونه وهو ماسكه بيده',
    en: 'Looking everywhere for a phone that is already in your hand',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-006',
    game: 'act',
    ar: 'يصبّ قهوة للجمع وتخلص الدلة عند آخر واحد',
    en: 'Pouring gahwa for everyone and the pot runs dry at the last guest',
    rooms: ['diwaniya', 'family', 'kuwait'],
    difficulty: 'medium',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-007',
    game: 'act',
    ar: 'يركن السيارة بالعكس والكل واقف يتفرج عليه',
    en: 'Reverse parking while everybody stands and watches',
    rooms: ['friends', 'kuwait', 'family'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-008',
    game: 'act',
    ar: 'ينتظر أذان المغرب والأكل قدامه',
    en: 'Waiting for the maghrib call to prayer with the food right in front of you',
    rooms: ['ramadan', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-009',
    game: 'act',
    ar: 'ياكل شي حار مرة ويتظاهر إنه عادي',
    en: 'Eating something extremely spicy and pretending it is fine',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-010',
    game: 'act',
    ar: 'يحاول يفتح مرطبان ما ينفتح ولا مع كل البيت',
    en: 'Trying to open a jar that nobody in the house can open',
    rooms: ['family', 'friends', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-011',
    game: 'act',
    ar: 'يعيد نفس السيلفي عشرين مرة',
    en: 'Retaking the same selfie twenty times',
    rooms: ['friends', 'couples', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-012',
    game: 'act',
    ar: 'يياي يطالب بالعيدية قبل العيد بيومين',
    en: 'A kid asking for the Eid money two days early',
    rooms: ['family', 'kids', 'ramadan', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-013',
    game: 'act',
    ar: 'واقف بزحمة شارع الخليج وما تحرّك من ربع ساعة',
    en: 'Stuck in Gulf Road traffic and not moving for fifteen minutes',
    rooms: ['kuwait', 'friends', 'diwaniya'],
    difficulty: 'medium',
    level: 'family',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-014',
    game: 'act',
    ar: 'يحاول يصحّي أخوه على السحور',
    en: 'Trying to wake your brother up for suhoor',
    rooms: ['ramadan', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-015',
    game: 'act',
    ar: 'يشيل أكياس الجمعية كلها بمشوار واحد',
    en: 'Carrying every grocery bag in one trip so you never come back',
    rooms: ['family', 'friends', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-016',
    game: 'act',
    ar: 'نسى وين ركن سيارته في مواقف المجمع',
    en: 'Forgetting where you parked in a huge mall car park',
    rooms: ['kuwait', 'friends', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-017',
    game: 'act',
    ar: 'يضغط كل أزرار ريموت المكيّف عسى شي يشتغل',
    en: 'Pressing every button on the AC remote hoping something works',
    rooms: ['family', 'friends', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-018',
    game: 'act',
    ar: 'قطوة قاعدة على مكانه وما تبي تقوم',
    en: 'A cat sitting in your seat and refusing to move',
    rooms: ['family', 'kids', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-019',
    game: 'act',
    ar: 'يتظاهر إنه يسمع كلامك وهو على التلفون',
    en: 'Pretending to listen to you while scrolling on the phone',
    rooms: ['friends', 'couples', 'family'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-020',
    game: 'act',
    ar: 'طلع من الحلاق بقصة ما طلبها',
    en: 'Leaving the barber with a haircut you did not ask for',
    rooms: ['friends', 'diwaniya', 'kuwait'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-021',
    game: 'act',
    ar: 'يطارد ذبانة في وسط الجلسة',
    en: 'Chasing one fly around the whole majlis',
    rooms: ['diwaniya', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-022',
    game: 'act',
    ar: 'أول يوم له في النادي ويبي يوري نفسه',
    en: 'First day at the gym and trying to look experienced',
    rooms: ['friends', 'kuwait'],
    difficulty: 'medium',
    level: 'friends',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-023',
    game: 'act',
    ar: 'يحاول يطوي شرشف السرير ويستسلم',
    en: 'Trying to fold a fitted bedsheet and giving up',
    rooms: ['family', 'couples', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-024',
    game: 'act',
    ar: 'يحاول ياكل صحن مجبوس كبير عليه مرتين',
    en: 'Facing a plate of machboos twice the size of you',
    rooms: ['family', 'diwaniya', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-025',
    game: 'act',
    ar: 'يسرق أكل من الثلاجة والكل نايم',
    en: 'Sneaking food from the fridge while everybody is asleep',
    rooms: ['family', 'friends', 'kids', 'ramadan'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-026',
    game: 'act',
    ar: 'واقف بطابور الجمعية قبل رمضان بيوم',
    en: 'Standing in the supermarket queue the day before Ramadan',
    rooms: ['ramadan', 'kuwait', 'family'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-027',
    game: 'act',
    ar: 'بطارية تلفونه ١٪ وينتظر مكالمة مهمة',
    en: 'Phone at one percent while waiting for an important call',
    rooms: ['friends', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-028',
    game: 'act',
    ar: 'يصوّر صورة جماعية وكل مرة واحد يغمّض',
    en: 'Taking a group photo where somebody always blinks',
    rooms: ['family', 'friends', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-029',
    game: 'act',
    ar: 'يبي يرقص في العرس بس مستحي',
    en: 'Wanting to dance at a wedding but too shy to start',
    rooms: ['friends', 'family', 'kuwait'],
    difficulty: 'medium',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-030',
    game: 'act',
    ar: 'ينتظر الدليفري ويطالع الباب كل دقيقة',
    en: 'Waiting for the delivery and checking the door every minute',
    rooms: ['friends', 'family', 'ramadan'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-031',
    game: 'act',
    ar: 'يركض على المصعد قبل ما يسكّر',
    en: 'Sprinting to catch the lift before the doors close',
    rooms: ['friends', 'kids', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-032',
    game: 'act',
    ar: 'يسمع قصة طويلة من جدّته ويتفاعل بأدب',
    en: 'Politely listening to your grandmother tell a very long story',
    rooms: ['family', 'diwaniya', 'kids'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-033',
    game: 'act',
    ar: 'يشرب چاي حار مرة ويتظاهر إنه بارد',
    en: 'Sipping boiling hot tea and pretending it is lukewarm',
    rooms: ['diwaniya', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-034',
    game: 'act',
    ar: 'يحاول يفتح باب مكتوب عليه اسحب وهو يدفع',
    en: 'Pushing a door that clearly says pull',
    rooms: ['friends', 'kids', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'act-035',
    game: 'act',
    ar: 'يوصّل خمس أشخاص وكل واحد بيته بمنطقة',
    en: 'Driving five friends home and every house is in a different area',
    rooms: ['friends', 'kuwait', 'diwaniya'],
    difficulty: 'medium',
    level: 'family',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
];
