import type { Prompt } from '../../engine/types';

/**
 * التحدي الأخير — Final Challenge.
 * These cards are *instructions to the table*, not things to guess. The host
 * reads them out loud, the round runs, and the host awards the points.
 */
export const FINAL_PROMPTS: Prompt[] = [
  {
    id: 'fin-001',
    game: 'final',
    ar: 'مثّل ثلاث كروت ورا بعض في ٣٠ ثانية',
    en: 'Act three cards in a row in 30 seconds',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'kids', 'ramadan', 'couples'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-002',
    game: 'final',
    ar: 'اثنين من الفريق يمثّلون نفس الكرت مع بعض',
    en: 'Two teammates act the same card together',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'kids', 'ramadan'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-003',
    game: 'final',
    ar: 'اشرح الكرت بثلاث كلمات بس',
    en: 'Explain the card using only three words',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'couples'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-004',
    game: 'final',
    ar: 'كل واحد بالفريق يقول كلمة وحدة بالدور',
    en: 'Every teammate contributes one word, in turn',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'kids'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-005',
    game: 'final',
    ar: 'الفريق الثاني يختار منو يمثّل',
    en: 'The other team chooses who performs',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'kids', 'ramadan'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-006',
    game: 'final',
    ar: 'مثّل وإيدينك ورا ظهرك',
    en: 'Act with your hands behind your back',
    rooms: ['friends', 'family', 'diwaniya', 'kids', 'kuwait'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-007',
    game: 'final',
    ar: 'مثّل وأنت قاعد ما تقوم من مكانك',
    en: 'Act while staying seated the whole time',
    rooms: ['friends', 'family', 'diwaniya', 'kids', 'ramadan'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-008',
    game: 'final',
    ar: 'وصّل الكرت بالأصوات بس، بدون حركات',
    en: 'Convey the card with sounds only, no gestures',
    rooms: ['friends', 'family', 'diwaniya', 'kids', 'kuwait'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-009',
    game: 'final',
    ar: 'مثّل وظهرك للفريق',
    en: 'Act with your back to your team',
    rooms: ['friends', 'diwaniya', 'kids', 'family'],
    difficulty: 'hard',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-010',
    game: 'final',
    ar: 'الفريق لازم يخمّن في ١٥ ثانية بس',
    en: 'The team has only 15 seconds to guess',
    rooms: ['friends', 'family', 'diwaniya', 'kuwait', 'kids', 'ramadan', 'couples'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-011',
    game: 'final',
    ar: 'كرّر كلمة وحدة بس بنبرات مختلفة',
    en: 'Repeat a single word in different tones only',
    rooms: ['friends', 'family', 'diwaniya', 'couples', 'kids'],
    difficulty: 'hard',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'fin-012',
    game: 'final',
    ar: 'واحد يمثّل وواحد يسوي الأصوات له',
    en: 'One performs, a teammate provides the sound effects',
    rooms: ['friends', 'family', 'diwaniya', 'kids', 'kuwait'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
];
