import type { Prompt } from '../../engine/types';

/**
 * قلّدها — Imitate It. Voice is allowed here.
 * Rule for this deck: character *types* and situations only. No living public
 * figures, no named individuals, no accents tied to a nationality.
 */
export const IMITATE_PROMPTS: Prompt[] = [
  {
    id: 'imi-001',
    game: 'imitate',
    ar: 'معلّق كورة يعلّق على شخص يفتح باب الثلاجة',
    en: 'A football commentator narrating somebody opening the fridge',
    rooms: ['friends', 'diwaniya', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-002',
    game: 'imitate',
    ar: 'واحد يفاصل على نص دينار نص ساعة',
    en: 'Somebody bargaining for half an hour over a tiny discount',
    rooms: ['friends', 'kuwait', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-003',
    game: 'imitate',
    ar: 'مدرب نادي يشوف واحد يرفع حديد بطريقة غلط',
    en: 'A gym coach watching somebody lift with terrible form',
    rooms: ['friends', 'kuwait'],
    difficulty: 'medium',
    level: 'friends',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-004',
    game: 'imitate',
    ar: 'واحد يعيد نفس مقطع السناب عشر مرات',
    en: 'Somebody recording the same ten-second story for the tenth time',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-005',
    game: 'imitate',
    ar: 'سايق يعرف كل طريق مختصر في البلد',
    en: 'A driver who knows every shortcut in the country',
    rooms: ['friends', 'kuwait', 'diwaniya'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-006',
    game: 'imitate',
    ar: 'معلّم ياخذ الحضور والصف كله يسولف',
    en: 'A teacher taking attendance while the class talks over them',
    rooms: ['kids', 'family', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-007',
    game: 'imitate',
    ar: 'واحد يلقي كلمة في عرس وما يبي يخلص',
    en: 'Somebody giving a wedding speech that will not end',
    rooms: ['family', 'friends', 'kuwait'],
    difficulty: 'medium',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-008',
    game: 'imitate',
    ar: 'ياهل يشرح لك قصة كرتون بكل التفاصيل',
    en: 'A kid explaining a cartoon plot with every single detail',
    rooms: ['kids', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-009',
    game: 'imitate',
    ar: 'إعلان في المطار عن رحلة تأخرت مرة ثانية',
    en: 'An airport announcement about a flight delayed again',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-010',
    game: 'imitate',
    ar: 'مذيع نشرة أخبار يقرأ خبر عن ضياع الريموت',
    en: 'A news anchor reporting that the TV remote is missing',
    rooms: ['family', 'friends', 'kids', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-011',
    game: 'imitate',
    ar: 'مرشد سياحي يشرح لك عن غرفة الجلوس',
    en: 'A tour guide presenting your own living room',
    rooms: ['friends', 'family', 'kids', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-012',
    game: 'imitate',
    ar: 'طبّاخ في برنامج طبخ يذوق أكلته ويبالغ',
    en: 'A TV chef tasting their own dish and overacting',
    rooms: ['family', 'friends', 'kids', 'ramadan'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-013',
    game: 'imitate',
    ar: 'واحد تعلّم كلمة يديدة ويحطها بكل جملة',
    en: 'Somebody who learned a new word and uses it in every sentence',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-014',
    game: 'imitate',
    ar: 'جدّة تصرّ إنك ما أكلت شي',
    en: 'A grandmother insisting you have not eaten anything',
    rooms: ['family', 'kids', 'diwaniya', 'ramadan'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-015',
    game: 'imitate',
    ar: 'ربيعك يقص قصة ويبدأ من قبل سنتين',
    en: 'A friend telling a story that starts two years before the point',
    rooms: ['friends', 'diwaniya', 'family'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-016',
    game: 'imitate',
    ar: 'واحد صحى قبل المنبّه ويتظاهر إنه نشيط',
    en: 'Somebody who woke up before the alarm and pretends to feel great',
    rooms: ['friends', 'family', 'ramadan'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-017',
    game: 'imitate',
    ar: 'واحد يعطيك العنوان بالعلامات: بعد الدوار وقبل الجمعية',
    en: 'Somebody giving directions only by landmarks, never street names',
    rooms: ['kuwait', 'friends', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-018',
    game: 'imitate',
    ar: 'مدرّب تحفيز يحمّسك لأنك قمت من السرير',
    en: 'A motivational speaker celebrating that you got out of bed',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-019',
    game: 'imitate',
    ar: 'الشخص اللي دايم يقول «أنا قلت لك من زمان»',
    en: 'The person who always says "I told you so"',
    rooms: ['friends', 'family', 'couples', 'diwaniya'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-020',
    game: 'imitate',
    ar: 'بائع في محل يمشي وراك في كل ممر',
    en: 'A shop assistant who follows you down every aisle',
    rooms: ['friends', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-021',
    game: 'imitate',
    ar: 'واحد يشرح لك خطة سفرته وهو ما حجز شي',
    en: 'Somebody explaining a travel plan with nothing booked',
    rooms: ['friends', 'couples', 'diwaniya'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'imi-022',
    game: 'imitate',
    ar: 'راعي الديوانية يرحّب فيك وأنت داخل من الباب',
    en: 'The host of a diwaniya welcoming you the second you walk in',
    rooms: ['diwaniya', 'kuwait', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
];
