import type { Prompt } from '../../engine/types';

/**
 * اقرأ شفايفي — Read My Lips.
 * Short, everyday sentences. Long or rare words are unreadable on lips, so
 * keep each card under about six words in both languages.
 */
export const LIPS_PROMPTS: Prompt[] = [
  {
    id: 'lip-001',
    game: 'lips',
    ar: 'القهوة باردة',
    en: 'The gahwa is cold',
    rooms: ['diwaniya', 'family', 'kuwait', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-002',
    game: 'lips',
    ar: 'وين ركنت السيارة؟',
    en: 'Where did you park the car?',
    rooms: ['friends', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-003',
    game: 'lips',
    ar: 'باقي لي خمس دقايق',
    en: 'I am five minutes away',
    rooms: ['friends', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-004',
    game: 'lips',
    ar: 'يبت الدقوس لو لا؟',
    en: 'Did you bring the daqoos?',
    rooms: ['kuwait', 'family', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-005',
    game: 'lips',
    ar: 'نزّل المكيّف شوي',
    en: 'Turn the AC down a little',
    rooms: ['family', 'diwaniya', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-006',
    game: 'lips',
    ar: 'منو أكل آخر قطعة؟',
    en: 'Who ate the last piece?',
    rooms: ['family', 'friends', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-007',
    game: 'lips',
    ar: 'بطاريتي خلصت',
    en: 'My battery is dead',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-008',
    game: 'lips',
    ar: 'أشوفك باچر الصبح',
    en: 'See you tomorrow morning',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-009',
    game: 'lips',
    ar: 'الأكل جاهز تعالوا',
    en: 'The food is ready',
    rooms: ['family', 'ramadan', 'diwaniya', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-010',
    game: 'lips',
    ar: 'نسيت المفاتيح بالبيت',
    en: 'I left my keys at home',
    rooms: ['friends', 'family', 'couples'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-011',
    game: 'lips',
    ar: 'لا تقول لأحد',
    en: 'Do not tell anybody',
    rooms: ['friends', 'couples', 'kids'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-012',
    game: 'lips',
    ar: 'هذي آخر جولة',
    en: 'This is the last round',
    rooms: ['friends', 'diwaniya', 'kids', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-013',
    game: 'lips',
    ar: 'الجو حار مرة اليوم',
    en: 'It is very hot today',
    rooms: ['kuwait', 'family', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-014',
    game: 'lips',
    ar: 'اتصل فيني بعد المغرب',
    en: 'Call me after sunset',
    rooms: ['ramadan', 'family', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-015',
    game: 'lips',
    ar: 'أنا يوعان مرة',
    en: 'I am really hungry',
    rooms: ['ramadan', 'family', 'friends', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-016',
    game: 'lips',
    ar: 'افتح الباب لو سمحت',
    en: 'Open the door please',
    rooms: ['family', 'kids', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-017',
    game: 'lips',
    ar: 'شنو اسم هالمطعم؟',
    en: 'What is this restaurant called?',
    rooms: ['friends', 'couples', 'family'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'lip-018',
    game: 'lips',
    ar: 'تعال شوف هالشي',
    en: 'Come and see this',
    rooms: ['friends', 'family', 'kids', 'couples'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
];

/**
 * بس صوت — Sound Only. No words, no gestures.
 * Every card must be reproducible with the mouth alone.
 */
export const SOUND_PROMPTS: Prompt[] = [
  {
    id: 'snd-001',
    game: 'sound',
    ar: 'سيارة إسعاف عالقة في الزحمة',
    en: 'An ambulance stuck in traffic',
    rooms: ['kuwait', 'friends', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-002',
    game: 'sound',
    ar: 'صبّة قهوة وتنقيز فناجيل',
    en: 'Gahwa being poured and cups clinking',
    rooms: ['diwaniya', 'family', 'kuwait'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-003',
    game: 'sound',
    ar: 'قطوة تبي أكل',
    en: 'A cat demanding food',
    rooms: ['family', 'kids', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-004',
    game: 'sound',
    ar: 'جمهور يشوف هدف في آخر دقيقة',
    en: 'A crowd watching a last-minute goal',
    rooms: ['friends', 'diwaniya', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-005',
    game: 'sound',
    ar: 'مطر على زجاج النافذة',
    en: 'Rain on a window',
    rooms: ['family', 'couples', 'kids'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-006',
    game: 'sound',
    ar: 'غلاية ماي تفور',
    en: 'A kettle boiling over',
    rooms: ['family', 'ramadan', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-007',
    game: 'sound',
    ar: 'تلفون يرن وبعدين يهتز على الطاولة',
    en: 'A phone ringing then buzzing on a table',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-008',
    game: 'sound',
    ar: 'واحد نايم ويشخر',
    en: 'Somebody snoring',
    rooms: ['friends', 'family', 'kids', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-009',
    game: 'sound',
    ar: 'جرس الباب يندق عشر مرات',
    en: 'A doorbell rung ten times in a row',
    rooms: ['family', 'kids', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-010',
    game: 'sound',
    ar: 'فشار في المايكرويف',
    en: 'Popcorn in the microwave',
    rooms: ['family', 'friends', 'kids', 'couples'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-011',
    game: 'sound',
    ar: 'طيارة تقلع',
    en: 'A plane taking off',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-012',
    game: 'sound',
    ar: 'ياهل يبچي وبعدين يهدأ',
    en: 'A baby crying then settling down',
    rooms: ['family', 'kids', 'couples'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-013',
    game: 'sound',
    ar: 'سيارة قديمة ما تبي تشتغل',
    en: 'An old car that will not start',
    rooms: ['friends', 'kuwait', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-014',
    game: 'sound',
    ar: 'هوا وغبار على النوافذ',
    en: 'Wind and dust hitting the windows',
    rooms: ['kuwait', 'family', 'friends'],
    difficulty: 'hard',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-015',
    game: 'sound',
    ar: 'خلاط يسوي عصير',
    en: 'A blender making juice',
    rooms: ['family', 'ramadan', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-016',
    game: 'sound',
    ar: 'مدفع الإفطار والأذان',
    en: 'The iftar cannon followed by the call to prayer',
    rooms: ['ramadan', 'family', 'kuwait'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-017',
    game: 'sound',
    ar: 'دجاجة وديك في الصبح',
    en: 'A rooster and hens at sunrise',
    rooms: ['kids', 'family', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'snd-018',
    game: 'sound',
    ar: 'باب يصرصر وينسكّر بقوة',
    en: 'A creaking door that slams shut',
    rooms: ['family', 'friends', 'kids'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
];
