import type { Prompt } from '../../engine/types';

/**
 * لا تقولها — Do Not Say It.
 * `ar` / `en` hold the target word. The forbidden lists hold the words a
 * describer would reach for first. Three to five per language, and the two
 * lists do not have to be literal translations of each other — each list is
 * tuned to how people actually describe the word in that language.
 */
export const TABOO_PROMPTS: Prompt[] = [
  {
    id: 'tab-001',
    game: 'taboo',
    ar: 'قهوة',
    en: 'Gahwa',
    forbiddenAr: ['فنجان', 'دلة', 'تمر', 'مرّة', 'صبّ'],
    forbiddenEn: ['coffee', 'cup', 'dates', 'bitter', 'pour'],
    rooms: ['diwaniya', 'family', 'kuwait', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-002',
    game: 'taboo',
    ar: 'دقوس',
    en: 'Daqoos',
    forbiddenAr: ['طماط', 'حار', 'صلصة', 'رز', 'مجبوس'],
    forbiddenEn: ['tomato', 'spicy', 'sauce', 'rice', 'machboos'],
    rooms: ['kuwait', 'family', 'friends', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-003',
    game: 'taboo',
    ar: 'ديوانية',
    en: 'Diwaniya',
    forbiddenAr: ['ريال', 'يلسة', 'چاي', 'بيت', 'ليل'],
    forbiddenEn: ['men', 'sitting', 'tea', 'house', 'evening'],
    rooms: ['diwaniya', 'kuwait', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-004',
    game: 'taboo',
    ar: 'رمضان',
    en: 'Ramadan',
    forbiddenAr: ['صيام', 'شهر', 'فطور', 'سحور', 'هلال'],
    forbiddenEn: ['fasting', 'month', 'iftar', 'suhoor', 'moon'],
    rooms: ['ramadan', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-005',
    game: 'taboo',
    ar: 'مجبوس',
    en: 'Machboos',
    forbiddenAr: ['رز', 'دجاج', 'بهار', 'غدا', 'كويتي'],
    forbiddenEn: ['rice', 'chicken', 'spices', 'lunch', 'Kuwaiti'],
    rooms: ['kuwait', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-006',
    game: 'taboo',
    ar: 'عيدية',
    en: 'Eidiya',
    forbiddenAr: ['فلوس', 'عيد', 'ياهل', 'عطية', 'يد'],
    forbiddenEn: ['money', 'Eid', 'kids', 'gift', 'cash'],
    rooms: ['family', 'kids', 'ramadan', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-007',
    game: 'taboo',
    ar: 'زحمة',
    en: 'Traffic',
    forbiddenAr: ['سيارة', 'شارع', 'تأخير', 'دوام', 'صف'],
    forbiddenEn: ['cars', 'road', 'late', 'work', 'queue'],
    rooms: ['kuwait', 'friends', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-008',
    game: 'taboo',
    ar: 'مكيّف',
    en: 'Air conditioner',
    forbiddenAr: ['بارد', 'صيف', 'ريموت', 'غرفة', 'حر'],
    forbiddenEn: ['cold', 'summer', 'remote', 'room', 'hot'],
    rooms: ['family', 'kuwait', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-009',
    game: 'taboo',
    ar: 'چاي كرك',
    en: 'Karak tea',
    forbiddenAr: ['حليب', 'چاي', 'هيل', 'كوب', 'حلو'],
    forbiddenEn: ['milk', 'tea', 'cardamom', 'cup', 'sweet'],
    rooms: ['kuwait', 'friends', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-010',
    game: 'taboo',
    ar: 'غبار',
    en: 'Sandstorm',
    forbiddenAr: ['تراب', 'هوا', 'سما', 'جو', 'صيف'],
    forbiddenEn: ['dust', 'wind', 'sky', 'weather', 'desert'],
    rooms: ['kuwait', 'family', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-011',
    game: 'taboo',
    ar: 'منبّه',
    en: 'Alarm clock',
    forbiddenAr: ['صباح', 'نوم', 'صوت', 'تلفون', 'يصحّي'],
    forbiddenEn: ['morning', 'sleep', 'sound', 'phone', 'wake'],
    rooms: ['family', 'friends', 'kids', 'ramadan'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-012',
    game: 'taboo',
    ar: 'حلاق',
    en: 'Barber',
    forbiddenAr: ['شعر', 'مقص', 'محل', 'قصة', 'لحية'],
    forbiddenEn: ['hair', 'scissors', 'shop', 'cut', 'beard'],
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-013',
    game: 'taboo',
    ar: 'سينما',
    en: 'Cinema',
    forbiddenAr: ['فيلم', 'شاشة', 'تذكرة', 'فشار', 'كرسي'],
    forbiddenEn: ['film', 'screen', 'ticket', 'popcorn', 'seat'],
    rooms: ['friends', 'couples', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-014',
    game: 'taboo',
    ar: 'صيد سمك',
    en: 'Fishing',
    forbiddenAr: ['بحر', 'خيط', 'سمك', 'طراد', 'صنارة'],
    forbiddenEn: ['sea', 'line', 'fish', 'boat', 'rod'],
    rooms: ['kuwait', 'friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-015',
    game: 'taboo',
    ar: 'جواز السفر',
    en: 'Passport',
    forbiddenAr: ['سفر', 'مطار', 'دولة', 'ختم', 'صورة'],
    forbiddenEn: ['travel', 'airport', 'country', 'stamp', 'photo'],
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-016',
    game: 'taboo',
    ar: 'صقر',
    en: 'Falcon',
    forbiddenAr: ['طير', 'قنص', 'ريش', 'سما', 'بر'],
    forbiddenEn: ['bird', 'hunting', 'feathers', 'sky', 'desert'],
    rooms: ['kuwait', 'diwaniya', 'family'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-017',
    game: 'taboo',
    ar: 'العيد الوطني',
    en: 'National Day',
    forbiddenAr: ['فبراير', 'علم', 'الكويت', 'احتفال', 'رش'],
    forbiddenEn: ['February', 'flag', 'Kuwait', 'celebration', 'parade'],
    rooms: ['kuwait', 'family', 'friends'],
    difficulty: 'medium',
    level: 'kids',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-018',
    game: 'taboo',
    ar: 'البحر',
    en: 'The sea',
    forbiddenAr: ['ماي', 'رمل', 'سباحة', 'موج', 'صيف'],
    forbiddenEn: ['water', 'sand', 'swimming', 'waves', 'summer'],
    rooms: ['kuwait', 'family', 'kids', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-019',
    game: 'taboo',
    ar: 'الواجب المدرسي',
    en: 'Homework',
    forbiddenAr: ['مدرسة', 'معلّم', 'دفتر', 'طالب', 'بيت'],
    forbiddenEn: ['school', 'teacher', 'notebook', 'student', 'home'],
    rooms: ['kids', 'family', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-020',
    game: 'taboo',
    ar: 'عرس',
    en: 'Wedding',
    forbiddenAr: ['عروس', 'زواج', 'قاعة', 'فستان', 'زفة'],
    forbiddenEn: ['bride', 'marriage', 'hall', 'dress', 'party'],
    rooms: ['family', 'friends', 'couples', 'kuwait'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-021',
    game: 'taboo',
    ar: 'جدّة',
    en: 'Grandmother',
    forbiddenAr: ['أم', 'كبيرة', 'بيت', 'حنّية', 'عيال'],
    forbiddenEn: ['mother', 'old', 'house', 'kind', 'family'],
    rooms: ['family', 'kids', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-022',
    game: 'taboo',
    ar: 'مباراة كرة قدم',
    en: 'Football match',
    forbiddenAr: ['كورة', 'قول', 'فريق', 'ملعب', 'حكم'],
    forbiddenEn: ['ball', 'goal', 'team', 'pitch', 'referee'],
    rooms: ['friends', 'diwaniya', 'kids', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-023',
    game: 'taboo',
    ar: 'قروب العائلة',
    en: 'The family group chat',
    forbiddenAr: ['واتساب', 'رسايل', 'أهل', 'صباح الخير', 'صور'],
    forbiddenEn: ['WhatsApp', 'messages', 'family', 'good morning', 'photos'],
    rooms: ['family', 'friends', 'diwaniya'],
    difficulty: 'medium',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-024',
    game: 'taboo',
    ar: 'الفطور بعد المغرب',
    en: 'Iftar',
    forbiddenAr: ['صيام', 'مغرب', 'أكل', 'رمضان', 'تمر'],
    forbiddenEn: ['fasting', 'sunset', 'food', 'Ramadan', 'dates'],
    rooms: ['ramadan', 'family', 'diwaniya'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-025',
    game: 'taboo',
    ar: 'مقلب',
    en: 'A prank',
    forbiddenAr: ['ضحك', 'كذب', 'صديق', 'تصوير', 'مفاجأة'],
    forbiddenEn: ['laugh', 'trick', 'friend', 'filming', 'surprise'],
    rooms: ['friends', 'kids', 'family'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-026',
    game: 'taboo',
    ar: 'رحلة برّية',
    en: 'A desert camping trip',
    forbiddenAr: ['بر', 'خيمة', 'نار', 'شتاء', 'ربع'],
    forbiddenEn: ['desert', 'tent', 'fire', 'winter', 'friends'],
    rooms: ['kuwait', 'friends', 'diwaniya', 'family'],
    difficulty: 'medium',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-027',
    game: 'taboo',
    ar: 'ذكرى قديمة',
    en: 'An old memory',
    forbiddenAr: ['زمان', 'صورة', 'طفولة', 'تذكّر', 'أيام'],
    forbiddenEn: ['past', 'photo', 'childhood', 'remember', 'days'],
    rooms: ['couples', 'family', 'diwaniya', 'friends'],
    difficulty: 'hard',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'tab-028',
    game: 'taboo',
    ar: 'موعد أول',
    en: 'A first date',
    forbiddenAr: ['حب', 'مطعم', 'توتر', 'لقاء', 'ورد'],
    forbiddenEn: ['love', 'restaurant', 'nervous', 'meeting', 'flowers'],
    rooms: ['couples', 'friends'],
    difficulty: 'medium',
    level: 'friends',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
];
