import type { Prompt } from '../../engine/types';

/**
 * منو فينا؟ — Who Among Us.
 * Safety rule for this deck: a card must be something a person would happily
 * be voted for in front of their family. No looks, no money, no relationships,
 * no health, no origin, no religion, no politics. When in doubt, cut it.
 */
export const WHO_PROMPTS: Prompt[] = [
  {
    id: 'who-001',
    game: 'who',
    ar: 'منو أكثر واحد يتأخر ويي بلا شي؟',
    en: 'Who is most likely to arrive late and bring nothing?',
    rooms: ['friends', 'diwaniya', 'family'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-002',
    game: 'who',
    ar: 'منو يطلب أكل بعد ما الكل يقول شبعنا؟',
    en: 'Who orders more food right after everybody says they are full?',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-003',
    game: 'who',
    ar: 'منو بيفتح مشروع جديد الأسبوع الياي؟',
    en: 'Who is most likely to start a new business next week?',
    rooms: ['friends', 'diwaniya', 'kuwait'],
    difficulty: 'easy',
    level: 'family',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-004',
    game: 'who',
    ar: 'منو يعرف كل الناس في الكويت؟',
    en: 'Who seems to know everybody in Kuwait?',
    rooms: ['friends', 'diwaniya', 'kuwait'],
    difficulty: 'easy',
    level: 'family',
    region: 'kw',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-005',
    game: 'who',
    ar: 'منو بيضيّع تلفونه في هالجلسة؟',
    en: 'Who is most likely to lose their phone during this gathering?',
    rooms: ['friends', 'family', 'diwaniya', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-006',
    game: 'who',
    ar: 'منو يرد على الرسايل بعد ثلاثة أيام؟',
    en: 'Who replies to messages three days later?',
    rooms: ['friends', 'family', 'couples'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-007',
    game: 'who',
    ar: 'منو يصوّر خمسين صورة عشان يختار وحدة؟',
    en: 'Who takes fifty photos to choose one?',
    rooms: ['friends', 'family', 'couples'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-008',
    game: 'who',
    ar: 'منو أول واحد بينام في الجلسة؟',
    en: 'Who will fall asleep first tonight?',
    rooms: ['friends', 'family', 'diwaniya', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-009',
    game: 'who',
    ar: 'منو صوته أعلى واحد في الجمعة؟',
    en: 'Who has the loudest voice in the room?',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-010',
    game: 'who',
    ar: 'منو يتطوّع يوصّل الكل بيوتهم؟',
    en: 'Who always volunteers to drive everybody home?',
    rooms: ['friends', 'diwaniya', 'family', 'kuwait'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-011',
    game: 'who',
    ar: 'منو ينسى اسم الشخص وهو يسولف وياه؟',
    en: 'Who forgets your name halfway through the conversation?',
    rooms: ['friends', 'diwaniya', 'family'],
    difficulty: 'medium',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-012',
    game: 'who',
    ar: 'منو يشتري شي ما يحتاجه لأن شكله حلو؟',
    en: 'Who buys something they do not need just because it looks nice?',
    rooms: ['friends', 'family', 'couples'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-013',
    game: 'who',
    ar: 'منو يرتب سفرة وما يروح؟',
    en: 'Who plans an entire trip and never goes?',
    rooms: ['friends', 'family', 'couples', 'diwaniya'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-014',
    game: 'who',
    ar: 'منو يخلّص آخر شي بالصحن؟',
    en: 'Who finishes the last thing on the plate?',
    rooms: ['family', 'friends', 'kids', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-015',
    game: 'who',
    ar: 'منو يضحك على نكتته قبل الكل؟',
    en: 'Who laughs at their own joke before anybody else?',
    rooms: ['friends', 'family', 'diwaniya', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-016',
    game: 'who',
    ar: 'منو أقرب واحد يصير مشهور على الإنترنت؟',
    en: 'Who is most likely to become famous online?',
    rooms: ['friends', 'family', 'kids'],
    difficulty: 'easy',
    level: 'family',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-017',
    game: 'who',
    ar: 'منو يخلّي القروب حيّ وما يسكت؟',
    en: 'Who keeps the group chat alive single-handedly?',
    rooms: ['friends', 'family', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-018',
    game: 'who',
    ar: 'منو يقول «خمس دقايق» ويتأخر ساعة؟',
    en: 'Who says "five minutes" and takes an hour?',
    rooms: ['friends', 'family', 'couples', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-019',
    game: 'who',
    ar: 'منو تروح له إذا تبي نصيحة صادقة؟',
    en: 'Who do you go to for honest advice?',
    rooms: ['friends', 'family', 'diwaniya', 'couples'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-020',
    game: 'who',
    ar: 'منو يتذكّر كل الذكريات القديمة بالتفصيل؟',
    en: 'Who remembers every old memory in detail?',
    rooms: ['family', 'friends', 'diwaniya', 'couples'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-021',
    game: 'who',
    ar: 'منو يفوز بأي لعبة نلعبها؟',
    en: 'Who wins whatever game we play?',
    rooms: ['kids', 'family', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-022',
    game: 'who',
    ar: 'منو يساعد بدون ما أحد يطلب منه؟',
    en: 'Who helps without anybody asking?',
    rooms: ['family', 'kids', 'diwaniya', 'friends'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-023',
    game: 'who',
    ar: 'منو يصير الطبّاخ إذا انقطع الأكل؟',
    en: 'Who becomes the cook when the food runs out?',
    rooms: ['family', 'friends', 'ramadan', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-024',
    game: 'who',
    ar: 'منو يصحّي الكل على السحور؟',
    en: 'Who wakes everybody up for suhoor?',
    rooms: ['ramadan', 'family', 'kids'],
    difficulty: 'easy',
    level: 'kids',
    region: 'gulf',
    enabled: true,
    pack: 'core',
  },
  {
    id: 'who-025',
    game: 'who',
    ar: 'منو يختار المطعم للجمعة كلها؟',
    en: 'Who picks the restaurant for the whole group?',
    rooms: ['friends', 'family', 'couples', 'diwaniya'],
    difficulty: 'easy',
    level: 'kids',
    region: 'global',
    enabled: true,
    pack: 'core',
  },
];
